#!/usr/bin/env node
// Generate all plugin distributions from plugins/spec.json and canonical skills.
import {
  existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmdirSync,
  unlinkSync, writeFileSync,
} from 'node:fs'
import { dirname, extname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { inflateRawSync } from 'node:zlib'
import ts from 'typescript'
import { desktopSource } from './desktop-source.mjs'
import { loadTypeScriptModule } from './load-typescript.mjs'
import { buildZip } from './zip.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pluginSkills = resolve(root, 'plugins/src/skills')
const notice = 'Generated by scripts/build-plugins.mjs. Edit the source, then rebuild.'
const { parseSkillMetadata } = loadTypeScriptModule(new URL('../packages/shared/src/skills/metadata.ts', import.meta.url))
const sort = (a, b) => a < b ? -1 : a > b ? 1 : 0
const posix = path => path.split(sep).join('/')
const label = path => posix(relative(root, path))
const lf = text => text.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n').replace(/\n*$/, '\n')
const json = value => lf(JSON.stringify(sorted(value), null, 2))
const readJson = path => JSON.parse(readFileSync(resolve(root, path), 'utf8'))
const escape = text => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const word = text => new RegExp(`(?<![\\p{L}\\p{N}_])${escape(text)}(?![\\p{L}\\p{N}_])`, 'iu')

function sorted(value) {
  if (Array.isArray(value)) return value.map(sorted)
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort(sort).map(key => [key, sorted(value[key])]))
  }
  return value
}

function assert(condition, message) {
  if (!condition) throw new Error(message)
}

function contained(parent, child) {
  const path = relative(parent, child)
  assert(path && path !== '..' && !path.startsWith(`..${sep}`) && !isAbsolute(path), `Path leaves its component: ${child}`)
}

function regular(path) {
  assert(lstatSync(path).isFile(), `Expected a regular file (no symlinks): ${label(path)}`)
  return readFileSync(path)
}

function walk(directory) {
  if (!existsSync(directory)) return []
  assert(lstatSync(directory).isDirectory(), `Expected a regular directory (no symlinks): ${label(directory)}`)
  return readdirSync(directory).sort(sort).flatMap(name => {
    const path = join(directory, name)
    const stat = lstatSync(path)
    assert(!stat.isSymbolicLink(), `Symlink refused: ${label(path)}`)
    if (stat.isDirectory()) return walk(path)
    assert(stat.isFile(), `Non-regular file refused: ${label(path)}`)
    return [path]
  })
}

async function modelNames() {
  const built = join(root, 'packages/shared/dist/index.js')
  let registry
  if (existsSync(built)) {
    registry = await import(pathToFileURL(built).href)
  } else if (existsSync(join(root, 'packages/shared/src/skills/content.ts'))) {
    registry = loadTypeScriptModule(join(root, 'packages/shared/src/index.ts'))
  } else {
    // A clean source checkout lacks the generated skill module. Load the facts
    // leaf and read the two literal exports with the compiler, without a build.
    registry = loadTypeScriptModule(join(root, 'packages/shared/src/prompts/model-facts.ts'))
    const path = join(root, 'packages/shared/src/operations/index.ts')
    const source = ts.createSourceFile(path, readFileSync(path, 'utf8'), ts.ScriptTarget.Latest, true)
    registry = { ...registry }
    for (const key of ['VIDEO_MODELS', 'IMAGE_MODELS']) {
      const declaration = source.statements.filter(ts.isVariableStatement)
        .flatMap(statement => [...statement.declarationList.declarations])
        .find(item => ts.isIdentifier(item.name) && item.name.text === key)
      let value = declaration?.initializer
      while (value && (ts.isAsExpression(value) || ts.isSatisfiesExpression(value))) value = value.expression
      assert(value && ts.isArrayLiteralExpression(value) && value.elements.every(ts.isStringLiteral), `Cannot read ${key} from ${label(path)}; build shared first.`)
      registry[key] = value.elements.map(item => item.text)
    }
  }
  const { MODEL_FACTS, VIDEO_MODELS, IMAGE_MODELS } = registry
  assert(MODEL_FACTS?.length && VIDEO_MODELS?.length && IMAGE_MODELS?.length, 'Shared model registry is empty.')
  return [...new Set([...MODEL_FACTS.flatMap(model => [model.id, model.label]), ...VIDEO_MODELS, ...IMAGE_MODELS])].sort(sort)
}

function frozenRules(models, paid) {
  return [
    ...models.map(name => [word(name), `model name/id "${name}"`]),
    [/\$\d/, 'frozen dollar price'],
    [/\b\d+(?:\.\d+)?\s*(?:credits?|cents)\b/i, 'frozen credit/cents amount'],
    [/\b\d{3,4}p\b/i, 'frozen resolution'],
    [/\b[248]K\b/i, 'frozen resolution'],
    [/\b\d{2,5}\s*[x×]\s*\d{2,5}\s*(?:pixels?|px)\b/i, 'frozen pixel resolution'],
    [/\b(?:up to|at most|maximum|max|capped at|limit(?:ed)? to)\s*[:=]?\s*\d+(?:\.\d+)?\s*[- ]?\s*(?:seconds?|secs?|s\b|(?:image |video |audio )?references?)\b/i, 'frozen duration/reference cap'],
    [/\b\d+(?:\.\d+)?\s*[- ]\s*(?:seconds?|secs?|references?)\s+(?:cap|limit|maximum)\b/i, 'frozen duration/reference cap'],
    ...paid.map(name => [word(name), `paid skill "${name}"`]),
  ]
}

function refuse(text, path, rules, startLine = 1, fixedLine = false) {
  for (const [regex, rule] of rules) {
    const match = regex.exec(text)
    if (match) throw new Error(`${path}:${startLine + (fixedLine ? 0 : text.slice(0, match.index).split('\n').length - 1)}: ${rule}: ${match[0]}`)
  }
}

function strings(value, path = '') {
  if (typeof value === 'string') return [[path, value]]
  if (!value || typeof value !== 'object') return []
  return Object.entries(value).filter(([key]) => key !== '$comment')
    .flatMap(([key, item]) => strings(item, path ? `${path}.${key}` : key))
}

function validateSpec(spec, source, rules) {
  const limits = { name: 64, displayName: 30, shortDescription: 30, description: 1024, longDescription: 4000, developerName: 80 }
  for (const [key, max] of Object.entries(limits)) {
    assert(typeof spec[key] === 'string' && spec[key].trim() && [...spec[key]].length <= max, `plugins/spec.json: ${key} must be nonempty and at most ${max} characters.`)
  }
  assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(spec.name), 'plugins/spec.json: invalid plugin name.')
  assert(Array.isArray(spec.capabilities) && spec.capabilities.length <= 20 && spec.capabilities.every(value => typeof value === 'string' && value.length && [...value].length <= 120), 'plugins/spec.json: capabilities must have at most 20 nonempty strings of at most 120 characters.')
  assert(Array.isArray(spec.defaultPrompts) && spec.defaultPrompts.length <= 3 && new Set(spec.defaultPrompts).size === spec.defaultPrompts.length, 'plugins/spec.json: at most 3 unique defaultPrompts are allowed.')
  for (const prompt of spec.defaultPrompts) {
    assert(typeof prompt === 'string' && prompt.trim() && [...prompt].length <= 128 && !/[\r\n@]/.test(prompt), 'plugins/spec.json: defaultPrompts must be one line, at most 128 characters, without @.')
  }
  for (const [key, value] of Object.entries({ homepage: spec.homepage, repository: spec.repository, authorURL: spec.author?.url, ...spec.urls })) {
    let valid = false
    try { valid = new URL(value).protocol === 'https:' } catch {}
    assert(typeof value === 'string' && [...value].length <= 1024 && valid, `plugins/spec.json: ${key} must be an HTTPS URL of at most 1024 characters.`)
  }
  for (const key of ['website', 'support', 'privacyPolicy', 'termsOfService']) assert(spec.urls?.[key], `plugins/spec.json: missing urls.${key}.`)
  for (const key of ['name', 'email']) assert(typeof spec.author?.[key] === 'string' && spec.author[key].trim(), `plugins/spec.json: missing author.${key}.`)
  assert(typeof spec.license === 'string' && spec.license.trim() && typeof spec.category === 'string' && spec.category.trim(), 'plugins/spec.json: license and category are required.')
  assert(Array.isArray(spec.keywords) && spec.keywords.every(value => typeof value === 'string' && value.trim()), 'plugins/spec.json: keywords must be strings.')
  assert(typeof spec.liveGuideFooter === 'string' && spec.liveGuideFooter.trim(), 'plugins/spec.json: liveGuideFooter is required.')
  assert(spec.mcpServer?.versionFrom === 'packages/mcp/package.json', 'plugins/spec.json: server version must come from packages/mcp/package.json.')
  const listing = { ...spec }
  delete listing.liveGuideFooter
  delete listing.icon
  delete listing.mcpServer
  for (const [field, value] of strings(listing)) {
    const offset = source.indexOf(JSON.stringify(value))
    const line = source.slice(0, Math.max(0, offset)).split('\n').length
    refuse(value, `plugins/spec.json (${field})`, rules, line, true)
    if (/^(?:displayName|shortDescription|description|longDescription|defaultPrompts(?:\.|$))/.test(field)) {
      refuse(value, `plugins/spec.json (${field})`, [[/\u2014/, 'em dash in listing copy']], line, true)
    }
  }
}

function generatedText(text, path) {
  text = lf(text)
  const extension = extname(path).toLowerCase()
  if (path.endsWith('/SKILL.md')) {
    assert(!/<!--\s*@/.test(text), `${path}: internal marker comment in generated skill.`)
    const frontmatter = /^---\n[\s\S]*?\n---(?:\n|$)/.exec(text)
    assert(frontmatter, `${path}:1: missing skill frontmatter`)
    return `${frontmatter[0]}<!-- ${notice} -->\n${text.slice(frontmatter[0].length)}`
  }
  if (extension === '.md' || extension === '.html') return `<!-- ${notice} -->\n${text}`
  if (['.yaml', '.yml', '.toml', '.py', '.sh', '.ps1'].includes(extension)) {
    return text.startsWith('#!') ? text.replace(/\n/, `\n# ${notice}\n`) : `# ${notice}\n${text}`
  }
  if (['.js', '.mjs', '.cjs', '.ts', '.css'].includes(extension)) {
    return extension === '.css' ? `/* ${notice} */\n${text}` : `// ${notice}\n${text}`
  }
  return text
}

function skillFiles(spec, rules) {
  const files = new Map()
  const skills = []
  for (const [tier, names] of Object.entries(spec.skills)) {
    assert(['shared', 'plugin'].includes(tier) && Array.isArray(names), `plugins/spec.json: invalid skills.${tier}.`)
    for (const name of names) {
      assert(typeof name === 'string' && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) && name.length <= 64, `Invalid skill name: ${name}`)
      assert(!skills.some(skill => skill.name === name), `Duplicate selected skill: ${name}`)
      refuse(name, `plugins/spec.json (skills.${tier})`, rules)
      const directory = join(pluginSkills, name)
      const source = tier === 'shared' ? join(root, 'packages/shared/skills', `${name}.md`) : join(directory, 'SKILL.md')
      assert(existsSync(source), `Missing ${tier} skill "${name}": ${source}.`)
      const input = tier === 'shared' ? [[source, 'SKILL.md']] : walk(directory).map(path => [path, posix(relative(directory, path))])
      for (const [path, child] of input) {
        const output = `skills/${name}/${child}`
        refuse(output, output, rules)
        let data = regular(path)
        let text
        try { if (!data.includes(0)) text = new TextDecoder('utf-8', { fatal: true }).decode(data) } catch {}
        if (text !== undefined) {
          if (tier === 'shared') {
            text = lf(text).replace(/^[\t ]*<!--[\t ]*@(?:(?!<!--|-->)[^\n])*-->[\t ]*\n/gm, '').trimEnd() + `\n\n${spec.liveGuideFooter}\n`
          }
          if (child.split('/').at(-1) === 'SKILL.md') {
            let metadata
            try { metadata = parseSkillMetadata(text, name) } catch (error) { throw new Error(`${output}:1: ${error.message}`) }
            if (child === 'SKILL.md') skills.push(metadata)
          }
          text = generatedText(text, output)
          refuse(text, output, rules)
          data = Buffer.from(text)
        }
        assert(child.split('/').at(-1) !== 'SKILL.md' || text !== undefined, `${output}:1: SKILL.md must be UTF-8 text.`)
        assert(!['hooks.json', '.app.json', '.mcp.json'].includes(child.split('/').at(-1)), `${output}: forbidden bundled component.`)
        files.set(output, data)
      }
    }
  }
  assert(skills.length, 'plugins/spec.json: no skills selected.')
  return { files, skills }
}

function codexManifest(spec, version, withServer) {
  return {
    name: spec.name, version, description: spec.description, author: spec.author,
    homepage: spec.homepage, repository: spec.repository, license: spec.license, keywords: spec.keywords,
    skills: './skills/', ...(withServer ? { mcpServers: './.mcp.json' } : {}),
    interface: {
      displayName: spec.displayName, shortDescription: spec.shortDescription, longDescription: spec.longDescription,
      developerName: spec.developerName, category: spec.category, capabilities: spec.capabilities,
      websiteURL: spec.urls.website, supportURL: spec.urls.support, privacyPolicyURL: spec.urls.privacyPolicy,
      termsOfServiceURL: spec.urls.termsOfService, defaultPrompt: spec.defaultPrompts,
      composerIcon: './assets/icon.png', logo: './assets/icon.png',
    },
  }
}

function readme(spec, skills, host) {
  const serverAdvice = host === 'openai'
    ? "The bundled `slates-connect` skill registers the Slates server with your host if it isn't registered yet."
    : "If you connected Slates from the app's Settings before, remove that older `slates` server registration so the tools are not listed twice."
  const github = new URL(spec.repository).pathname.replace(/^\/|\/$/g, '').replace(/\.git$/, '')
  const install = host === 'claude' ? 'Install this plugin from the Claude directory.'
    : host === 'openai' ? 'Install this plugin from the ChatGPT or Codex plugin directory.'
    : `### Codex\n\n\`\`\`text\ncodex plugin marketplace add ${github}\ncodex plugin add ${spec.name}@${spec.name}\n\`\`\`\n\n### Claude Code\n\n\`\`\`text\n/plugin marketplace add ${github}\n/plugin install ${spec.name}@${spec.name}\n\`\`\``
  const text = generatedText(`# ${spec.displayName}\n\n${spec.longDescription}\n\n## What you need\n\nKeep the Slates desktop app running while your AI works on your projects. If it isn't installed or connected yet, the bundled \`slates-connect\` skill walks you through it.\n\n## Install\n\n${install}\n\n${serverAdvice}\n\n## Bundled skills\n\n${skills.map(skill => `- **${skill.name}**: ${skill.description}`).join('\n')}\n\n## Links\n\n- [Website](${spec.urls.website})\n- [Support](${spec.urls.support})\n- [Privacy policy](${spec.urls.privacyPolicy})\n- [Terms of service](${spec.urls.termsOfService})\n- [Source](${spec.repository})\n`, 'README.md')
  const prose = text.replace(/<!--[^]*?-->/g, '').replace(/^\s*(`{3,}|~{3,})[^\n]*\n[^]*?^\s*\1\s*$/gm, '')
  assert((prose.match(/\S+/g) || []).length >= 40, 'README.md: needs at least 40 words outside code blocks.')
  return text
}

function validateZip(zip, expected) {
  // Read the actual ZIP back: verify sorted regular-file entries and payloads.
  let offset = 0
  for (const { name, data } of expected) {
    assert(zip.readUInt32LE(offset) === 0x04034b50, `ZIP: missing local entry ${name}`)
    const method = zip.readUInt16LE(offset + 8)
    const size = zip.readUInt32LE(offset + 18)
    const length = zip.readUInt16LE(offset + 26)
    const extra = zip.readUInt16LE(offset + 28)
    assert(zip.subarray(offset + 30, offset + 30 + length).toString('utf8') === name, `ZIP: wrong entry ${name}`)
    const start = offset + 30 + length + extra
    const body = zip.subarray(start, start + size)
    assert((method === 8 ? inflateRawSync(body) : body).equals(data), `ZIP: wrong payload ${name}`)
    offset = start + size
  }
  for (const { name } of expected) {
    assert(zip.readUInt32LE(offset) === 0x02014b50 && (zip.readUInt32LE(offset + 38) >>> 16) === 0o100644, `ZIP: ${name} must be a regular file.`)
    offset += 46 + zip.readUInt16LE(offset + 28) + zip.readUInt16LE(offset + 30) + zip.readUInt16LE(offset + 32)
  }
  assert(zip.readUInt32LE(offset) === 0x06054b50 && zip.readUInt16LE(offset + 10) === expected.length && offset + 22 === zip.length, 'ZIP: invalid entry count/end record.')
}

function compareOrWrite(directory, files, check) {
  const target = resolve(root, directory)
  contained(root, target)
  const actual = walk(target)
  const wanted = new Set(files.keys())
  let differences = 0
  for (const path of actual) {
    if (!wanted.has(posix(relative(target, path)))) {
      if (check) { console.error(`extra: ${label(path)}`); differences++ }
      else { contained(target, path); unlinkSync(path) }
    }
  }
  if (!check && existsSync(target)) {
    const prune = path => {
      for (const name of readdirSync(path)) {
        const child = join(path, name)
        if (lstatSync(child).isDirectory()) { prune(child); if (!readdirSync(child).length) { contained(target, child); rmdirSync(child) } }
      }
    }
    prune(target)
  }
  for (const [name, data] of files) {
    const path = resolve(target, name)
    contained(target, path)
    if (check) {
      if (!existsSync(path)) { console.error(`missing: ${label(path)}`); differences++ }
      else if (!regular(path).equals(data)) { console.error(`different: ${label(path)}`); differences++ }
    } else { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, data) }
  }
  return differences
}

async function main() {
  const args = process.argv.slice(2)
  assert(args.length <= 1 && args.every(arg => ['--check', '--self-test', '--list-banned'].includes(arg)), 'Usage: node scripts/build-plugins.mjs [--check|--self-test|--list-banned]')
  const models = await modelNames()
  if (args.includes('--list-banned')) { console.log(models.join('\n')); return }
  const specSource = readFileSync(join(root, 'plugins/spec.json'), 'utf8')
  const spec = JSON.parse(specSource)
  const { version, name: packageName } = readJson('packages/mcp/package.json')
  assert(/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(version) && spec.mcpServer?.package === packageName, 'MCP package/version must match packages/mcp/package.json and use an exact version.')
  const { paidSkills } = readJson('dist-pack/pack-manifest.json')
  assert(Array.isArray(paidSkills) && paidSkills.length && paidSkills.every(name => typeof name === 'string' && name), 'dist-pack/pack-manifest.json: paidSkills must be nonempty.')
  const rules = frozenRules(models, paidSkills)
  validateSpec(spec, specSource, rules)
  const { files: skills, skills: metadata } = skillFiles(spec, rules)
  if (args.includes('--self-test')) {
    const [path, body] = [...skills].find(([name]) => name.endsWith('/SKILL.md'))
    for (const [token, rule] of [[models[0], 'model name/id'], [paidSkills[0], 'paid skill']]) {
      let refused = false
      try { refuse(`${body.toString('utf8')}\n${token}\n`, path, rules) } catch (error) { refused = error.message.includes(rule); console.log(`self-test: ${error.message}`) }
      assert(refused, `Self-test failed: ${rule} was not refused.`)
    }
    console.log('plugins self-test passed: model and paid skill refused.')
    return
  }
  let iconPath, icon
  try {
    iconPath = desktopSource(spec.icon.desktopPath)
    icon = regular(iconPath)
  } catch (error) {
    // desktopSource also refuses an explicitly named missing desktop in CI.
    if (!process.env.CI || !(error.code === 'ENOENT' || error.message.startsWith('Missing desktop source:'))) throw error
    console.error('[build-plugins] WARNING: desktop icon was not checked; using the committed plugin icon.')
    iconPath = join(root, 'plugins/slates/assets/icon.png')
    icon = regular(iconPath)
  }
  assert(icon.length >= 33 && icon.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) && icon.readUInt32BE(8) === 13 && icon.subarray(12, 16).toString('ascii') === 'IHDR', `${label(iconPath)}: invalid PNG IHDR.`)
  const width = icon.readUInt32BE(16), height = icon.readUInt32BE(20)
  assert(width === height && width >= 48 && width <= 4096, `${label(iconPath)}: icon must be square and 48-4096 pixels.`)
  const license = Buffer.from(lf(regular(join(root, 'LICENSE')).toString('utf8')))
  const claude = { name: spec.name, displayName: spec.displayName, version, description: spec.description, author: spec.author, homepage: spec.homepage, repository: spec.repository, license: spec.license, keywords: spec.keywords, supportUrl: spec.urls.support, privacyPolicyUrl: spec.urls.privacyPolicy, termsOfServiceUrl: spec.urls.termsOfService }
  const mcp = pinned => ({ mcpServers: { [spec.mcpServer.name]: { command: 'npx', args: ['-y', `${packageName}${pinned ? `@${version}` : ''}`] } } })
  const packageFiles = (host, pinned = false) => new Map([
    ...(host === 'both' || host === 'openai' ? [['.codex-plugin/plugin.json', Buffer.from(json(codexManifest(spec, version, host === 'both')))]] : []),
    ...(host !== 'openai' ? [['.claude-plugin/plugin.json', Buffer.from(json(claude))], ['.mcp.json', Buffer.from(json(mcp(pinned)))]] : []),
    ...[...skills].sort(([a], [b]) => sort(a, b)), ['assets/icon.png', icon],
    ['README.md', Buffer.from(readme(spec, metadata, host))], ['LICENSE', license],
  ])
  const own = packageFiles('both'), directory = packageFiles('claude', true), openai = packageFiles('openai')
  for (const [name, files] of [['plugins/slates', own], ['plugins/slates-claude-directory', directory], ['dist-plugins/slates-openai-directory.zip', openai]]) {
    for (const [path, data] of files) {
      if (path === 'README.md' || path.endsWith('.json')) refuse(data.toString('utf8'), `${name}/${path}`, rules)
    }
  }
  const zipManifest = JSON.parse(openai.get('.codex-plugin/plugin.json').toString('utf8'))
  assert(['apps', 'hooks', 'mcpServers'].every(key => !Object.hasOwn(zipManifest, key)), 'OpenAI manifest has a forbidden component field.')
  const entries = [...openai].sort(([a], [b]) => sort(a, b)).map(([name, data]) => ({ name, data }))
  const zip = buildZip(entries)
  validateZip(zip, entries)
  const codexMarket = { name: spec.name, interface: { displayName: spec.displayName }, plugins: [{ name: spec.name, source: { source: 'local', path: './plugins/slates' }, policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' }, category: spec.category }] }
  const claudeMarket = { name: spec.name, owner: spec.author, plugins: [{ name: spec.name, source: './plugins/slates', description: spec.description, category: spec.category }], metadata: { description: spec.description } }
  const check = args.includes('--check')
  let differences = compareOrWrite('plugins/slates', own, check) + compareOrWrite('plugins/slates-claude-directory', directory, check)
  for (const [path, value] of [['.agents/plugins/marketplace.json', codexMarket], ['.claude-plugin/marketplace.json', claudeMarket]]) {
    const data = Buffer.from(json(value)), absolute = resolve(root, path)
    refuse(data.toString('utf8'), path, rules)
    if (check) {
      if (!existsSync(absolute)) { console.error(`missing: ${path}`); differences++ }
      else if (!regular(absolute).equals(data)) { console.error(`different: ${path}`); differences++ }
    } else { mkdirSync(dirname(absolute), { recursive: true }); writeFileSync(absolute, data) }
  }
  if (!check) { mkdirSync(join(root, 'dist-plugins'), { recursive: true }); writeFileSync(join(root, 'dist-plugins/slates-openai-directory.zip'), zip) }
  assert(!differences, `plugins check failed: ${differences} differing, missing or extra paths.`)
  console.log(`plugins ${check ? 'check passed' : 'built'}: 3 packages, ${metadata.length} skills each, version ${version}.`)
}

main().catch(error => { console.error(`[build-plugins] ${error.message}`); process.exitCode = 1 })
