/** Product fan-out policy: one provider request and debit per output.
 * This is NOT a model capability or provider batch limit. Desktop mirror is
 * generated by slate/scripts/sync-generation-policy.mjs; never edit it there. */
export const IMAGE_QUANTITIES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const
export const MAX_IMAGE_VARIATIONS = IMAGE_QUANTITIES[IMAGE_QUANTITIES.length - 1]
export type ImageQuantity = typeof IMAGE_QUANTITIES[number]
export const clampImageQuantity = (count: number = 1): ImageQuantity =>
  Math.max(1, Math.min(MAX_IMAGE_VARIATIONS, Number.isFinite(count) ? Math.floor(count) : 1)) as ImageQuantity

/** Default saved-recipe framing, shared by composer restore, quote and dispatch. */
export const DEFAULT_SHOT_ASPECT_RATIO = '16:9' as const

/**
 * The built-in tools, and the seat each one renders on when its caller names no
 * model. THE ONE HOME, for both repos: the desktop reads it through its generated
 * mirror (`toolModel` in slate/src/shared/pricing.ts), this package reads it for
 * the op descriptions and the generated skill partial.
 *
 * `'default-image'` means "follow the app's default image model"
 * (`defaultModelFor('image')` in model-facts.ts), so promoting a better image
 * model moves these tools with it and nothing else is edited. A model id pins a
 * tool instead, for a reason recorded beside it. This file stays a
 * dependency-free leaf (it is copied verbatim into the desktop), which is why
 * the seat is a token each consumer resolves rather than a call made here.
 *
 * Before 2026-09-21 the sheet tools' model was typed at every use on the desktop
 * and twice more here (an op description and a skill), so three screens quoted
 * a sheet from one typed id while the handler billed from another.
 */
export const BUILT_IN_TOOLS = ['character-sheet', 'environment-plate', 'grid-extract', 'image-edit'] as const
export type BuiltInTool = typeof BUILT_IN_TOOLS[number]
export const DEFAULT_IMAGE_SEAT = 'default-image' as const
export const TOOL_SEAT: Record<BuiltInTool, typeof DEFAULT_IMAGE_SEAT | string> = {
  'character-sheet': DEFAULT_IMAGE_SEAT,
  'environment-plate': DEFAULT_IMAGE_SEAT,
  // Pinned: the image viewer offers these two tools a fixed short list of seats,
  // and the cell-extraction prompt has a variant per seat family. Moving either
  // is a picker and a prompt change first.
  'grid-extract': 'nano-banana-2',
  'image-edit': 'nano-banana-2',
}

/** Both sheet tools frame one wide image. On GPT Image the aspect is part of the price. */
export const SHEET_TOOL_ASPECT_RATIO = '16:9' as const

/**
 * The GPT Image tier a sheet tool pins. It read 'medium' until 2026-09-09: GPT
 * Image 2.5 renamed the ladder, so the tier GPT Image 2 called `medium` is now
 * `high`, and a stored 'medium' would have kept compiling while naming a
 * materially cheaper tier. Sheets are the identity lane (every downstream shot
 * inherits this frame's likeness), so this is deliberately not the draft tier.
 */
export const SHEET_TOOL_GPT_QUALITY = 'high' as const
