// Prebuild step: embed packages/shared/skills/*.md into a generated TS
// module so both surfaces can serve skill content without shipping (or
// resolving) loose .md files at runtime. The CLI's `slates install-skills`
// writes these to .claude/skills/<name>/SKILL.md; the MCP-only path reads
// them via the slates_get_prompting_guide op.
//
// Output: packages/shared/src/skills/content.ts (gitignored, regenerated
// on every build/typecheck). Each file's content is JSON.stringify'd so
// backticks / ${ / backslashes in the markdown can't break the module.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = join(here, '..')
const skillsDir = join(pkgRoot, 'skills')
const outDir = join(pkgRoot, 'src', 'skills')
const outFile = join(outDir, 'content.ts')

const files = readdirSync(skillsDir)
  .filter((f) => f.endsWith('.md'))
  .sort()

if (files.length === 0) {
  console.error(`[embed-skills] no .md files found in ${skillsDir}`)
  process.exit(1)
}

let out = '// GENERATED — do not edit. Source: packages/shared/skills/*.md\n'
out += '// Regenerated by scripts/embed-skills.mjs on every build.\n\n'
out += 'export const SKILLS: Record<string, string> = {\n'
for (const f of files) {
  const name = basename(f, '.md')
  const content = readFileSync(join(skillsDir, f), 'utf8')
  out += `  ${JSON.stringify(name)}: ${JSON.stringify(content)},\n`
}
out += '}\n'

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, out)
console.log(`[embed-skills] embedded ${files.length} skill(s) into src/skills/content.ts`)
